version: "3.7"

services:
  app:
    build:
      target: production
      dockerfile: Dockerfile
    command: node dist/app.js
    environment:
        - DATABASE_HOST=gc-database
        - DATABASE_PORT=5432
    ports:
      - "3000:3000"      
volumes:
    gc-data: