version: "3.7"

services:
  postgres-database:
    image: postgres:11
    ports:
        - 5433:5432
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: gc-database
    volumes:
        - gc-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: service
    command: yarn dev
    environment:
        - DATABASE_HOST=gc-database
        - DATABASE_PORT=5432
    ports:
      - "3000:3000"      
volumes:
    gc-data: